# Generated by Django 3.2.4 on 2021-06-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0005_ntjerseydetails_availabilty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubjerseydetails',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='clubjerseydetails',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
