# Generated by Django 3.2.4 on 2021-06-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0009_auto_20210622_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubjerseydetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ntjerseydetails',
            name='description',
        ),
    ]
