# Generated by Django 3.2.4 on 2021-06-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0011_customer_order_orderitem_shippinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='national_jersey',
            new_name='jersey',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='club_jersey',
        ),
    ]
