# Generated by Django 3.2.4 on 2021-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0015_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntjerseydetails',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ntjerseydetails',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, null=True),
        ),
    ]
