# Generated by Django 3.2.4 on 2021-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0028_auto_20210629_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
