# Generated by Django 3.2.4 on 2021-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JerseyDetails',
            new_name='ClubJerseyDetails',
        ),
    ]
