# Generated by Django 3.2.4 on 2021-06-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0003_ntjerseydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntjerseydetails',
            name='availabilty',
        ),
    ]
