# Generated by Django 3.2.4 on 2021-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0004_remove_ntjerseydetails_availabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntjerseydetails',
            name='availabilty',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=50, null=True),
        ),
    ]
