# Generated by Django 3.2.4 on 2021-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0006_auto_20210620_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntjerseydetails',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='ntjerseydetails',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
