# Generated by Django 3.2.4 on 2021-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0008_auto_20210621_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjerseydetails',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clubjerseydetails',
            name='type',
            field=models.CharField(blank=True, choices=[('Fan Version', 'Fan Version'), ('Player Version', 'Player Version')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ntjerseydetails',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ntjerseydetails',
            name='type',
            field=models.CharField(blank=True, choices=[('Fan Version', 'Fan Version'), ('Player Version', 'Player Version')], max_length=50, null=True),
        ),
    ]
