# Generated by Django 3.2.4 on 2021-06-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0012_auto_20210624_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_jersey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jerseyshop.clubjerseydetails')),
                ('national_jersey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jerseyshop.ntjerseydetails')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='jersey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jerseyshop.jersey'),
        ),
    ]
