# Generated by Django 3.2.4 on 2021-06-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0016_auto_20210624_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntjerseydetails',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ntjerseydetails',
            name='size',
        ),
    ]
