# Generated by Django 3.2.4 on 2021-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0017_auto_20210624_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjerseydetails',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ntjerseydetails',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
