# Generated by Django 3.2.4 on 2021-06-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerseyshop', '0020_auto_20210624_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jerseyshop.customer'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
